# Registers the Prusa Status bridge to start automatically (hidden) at every
# login via a Windows Scheduled Task, and starts it now.
# Writes bridge/run-hidden.vbs locally (gitignored; do not commit).
#
# Usage:  ./install-autostart.ps1 [-Port 37655] [-TaskName "PrusaStatusBridge"]
# Remove: ./uninstall-autostart.ps1
param(
    [int]$Port = 37655,
    [string]$TaskName = "PrusaStatusBridge"
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
    Write-Error "Node.js was not found on PATH. Install Node 18+ and try again."
    exit 1
}
$nodePath = $nodeCmd.Source
$serverPath = Join-Path $scriptDir "bridge-server.mjs"
$vbsPath = Join-Path $scriptDir "run-hidden.vbs"

if (-not (Test-Path $serverPath)) {
    Write-Error "Bridge server not found: $serverPath"
    exit 1
}

# Generate a tiny VBScript launcher so node runs with NO console window.
# wscript.exe is a GUI-subsystem host, so the Scheduled Task shows nothing.
$vbs = @"
' Auto-generated by install-autostart.ps1 - launches the bridge with no window.
Set sh = CreateObject("WScript.Shell")
sh.Environment("PROCESS")("PORT") = "$Port"
sh.CurrentDirectory = "$scriptDir"
sh.Run """$nodePath"" ""$serverPath""", 0, False
"@
Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII
Write-Host "Wrote launcher: $vbsPath" -ForegroundColor DarkGray

$action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$vbsPath`""
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::Zero)
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask -TaskName $TaskName `
    -Action $action -Trigger $trigger -Settings $settings -Principal $principal `
    -Description "Serves PrusaLink status to the iCUE Xeneon Edge widget on http://127.0.0.1:$Port" | Out-Null

Write-Host "Registered scheduled task '$TaskName' (starts at login on port $Port)." -ForegroundColor Green

Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 2
Write-Host "Started. Verify: http://127.0.0.1:$Port/health" -ForegroundColor Cyan
